import fs from 'node:fs';
import {spawnSync} from 'node:child_process';
import {ROOT,validate} from './library.mjs';
console.log(validate(ROOT));
const result=spawnSync('latexmk',['-pdfdvi','-interaction=nonstopmode','-halt-on-error','main.tex'],{cwd:ROOT,stdio:'inherit'});
if(result.error)throw result.error;
if(result.status!==0)process.exit(result.status||1);
const log=fs.readFileSync(ROOT+'/main.log','utf8');
if(/Citation .* undefined|There were undefined references/.test(log))throw new Error('Undefined citations');
fs.copyFileSync(ROOT+'/main.pdf',ROOT+'/paper-reading-notes.pdf');
